#!/usr/bin/env python3
# Copyright (c) 2026 inovex GmbH
#
# SPDX-License-Identifier: Apache-2.0

"""The coverage of each component: one table row per requirement component.

A software requirement (``ZEP-SRS-*``) has a ``component`` field (Threads,
Semaphore, ...). Zephyr's ``gen_requirements.py`` sets it and writes one page
per component. The traceability views of the requirements document show, for
each component, how many of its requirements each layer reaches: tests
(``verifies``), code (``satisfies``), design (``fulfills``) and coverage
adequacy (``assesses``).

sphinx-needs cannot group a table by a field. So this script reads the
component names from the generated requirement pages and writes one row per
component. Each cell is a ``need_count`` role, so Sphinx counts the needs at
build time; the script counts nothing. A new requirement changes the numbers
without a new run of this script; a new component needs one (the
``component-gen`` target runs on each build).

Writes ``traceability/components.rst``, copied into the requirements document
by its conf.py.
"""

import argparse
import re
import sys
from pathlib import Path

#: The software requirement pages of gen_requirements.py, one per component.
PAGES = "zephyr_software_requirements_*.rst"

_ID = re.compile(r"^\s+:id: (ZEP-SRS-\d+)-\d+\s*$")
_COMPONENT = re.compile(r"^\s+:component: (.+?)\s*$")

SRS = "type == 'req' and id.startswith('ZEP-SRS-')"

#: (column title, the filter after SRS and the component) for requirement needs.
COLUMNS = [
    ("Requirements", ""),
    ("Verified", "len(verifies_back) > 0"),
    ("Satisfied", "len(satisfies_back) > 0"),
    ("Designed", "len(fulfills_back) > 0"),
    (
        "All three",
        "len(verifies_back) > 0 and len(satisfies_back) > 0 and len(fulfills_back) > 0",
    ),
    ("Adequacy assessed", "len(assesses_back) > 0"),
]

#: The last column counts adequacy needs, not requirements. A filter of
#: ``need_count`` has no ``needs`` mapping, so it cannot read the verdict of a
#: requirement's adequacy need. It selects the adequacy needs by the id prefix
#: of the requirement they assess instead (one prefix per component).
ADEQUACY_TRUE = ("Adequacy true", "type == 'adequacy' and verdict == 'true'")


def components(gen_dir):
    """``{component: id prefix}`` from the generated requirement pages.

    The prefix is ``ZEP-SRS-<n>`` of the requirements of the component. Fails if
    a component has more than one prefix: the adequacy column needs one.
    """
    prefixes = {}
    for page in sorted(Path(gen_dir).glob(PAGES)):
        prefix = None
        for line in page.read_text().split("\n"):
            m = _ID.match(line)
            if m:
                prefix = m.group(1)
                continue
            m = _COMPONENT.match(line)
            if m and prefix:
                prefixes.setdefault(m.group(1), set()).add(prefix)
                prefix = None
    bad = sorted(c for c, p in prefixes.items() if len(p) != 1)
    if bad:
        raise ValueError(f"components with more than one id prefix: {', '.join(bad)}")
    return {c: p.pop() for c, p in sorted(prefixes.items())}


def _filter(component, extra):
    parts = [SRS, f"component == '{component}'"]
    if extra:
        parts.append(extra)
    return " and ".join(parts)


def _adequacy_filter(prefix):
    return f"{ADEQUACY_TRUE[1]} and len(assesses) > 0 and assesses[0].startswith('{prefix}-')"


def render(prefixes):
    out = [
        "Components",
        "==========",
        "",
        "Generated by ``doc/_scripts/component_gen.py``. One row per component of",
        "the software requirements (``ZEP-SRS-*``). Sphinx counts each cell from the",
        "needs at build time.",
        "",
        "* **Verified:** at least one test case verifies the requirement.",
        "* **Satisfied:** at least one symbol satisfies it.",
        "* **Designed:** at least one design element fulfills it.",
        "* **All three:** verified, satisfied and designed.",
        "* **Adequacy assessed:** the coverage run ran at least one of its verifying",
        "  test cases.",
        "* **Adequacy true:** its own tests run every symbol that coverage can judge.",
        "",
        ".. list-table:: Coverage per component",
        "   :header-rows: 1",
        "   :stub-columns: 1",
        "",
        "   * - Component",
    ]
    out += [f"     - {title}" for title, _ in (*COLUMNS, ADEQUACY_TRUE)]
    for name, prefix in prefixes.items():
        out.append(f"   * - {name}")
        out += [f"     - :need_count:`{_filter(name, extra)}`" for _, extra in COLUMNS]
        out.append(f"     - :need_count:`{_adequacy_filter(prefix)}`")
    out.append("   * - All")
    out += [
        f"     - :need_count:`{SRS + (' and ' + extra if extra else '')}`" for _, extra in COLUMNS
    ]
    out.append(f"     - :need_count:`{ADEQUACY_TRUE[1]}`")
    return "\n".join(out) + "\n"


def _write(path, text):
    """Write only if the content changed, so a rebuild does not re-read it."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.is_file() or path.read_text() != text:
        path.write_text(text)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--requirements-rst", required=True,
        help="the generated/ directory of gen_requirements.py",
    )
    parser.add_argument("--rst-out", required=True)
    args = parser.parse_args(argv)
    try:
        names = components(args.requirements_rst)
    except ValueError as e:
        print(f"component_gen: error: {e}", file=sys.stderr)
        return 1
    if not names:
        print(f"component_gen: error: no component in {args.requirements_rst}/{PAGES}",
              file=sys.stderr)
        return 1
    if any("'" in n for n in names):
        print("component_gen: error: a component name has a quote", file=sys.stderr)
        return 1
    _write(Path(args.rst_out) / "traceability" / "components.rst", render(names))
    print(f"component_gen: {len(names)} components")
    return 0


if __name__ == "__main__":
    sys.exit(main())
