#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Doxygen input filter to automatically define all CONFIG_* symbols found in a file.

This script scans a source file for any #ifdef CONFIG_... statements,
collects all unique symbols, and then prints a series of #define statements
for them before printing the original file content.

This allows Doxygen to parse all conditional blocks without needing to
manually update the PREDEFINED tag in the Doxyfile.
"""

import sys
import os
import re

def process_file(file_path):
    """
    Processes a single source file, prepends it with #defines, and prints to stdout.

    Args:
        file_path (str): The path to the file to process.
    """

    sys.stderr.write(f"[LOG] Filtering file: {os.path.basename(file_path)}\n")

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except IOError as e:
        sys.stderr.write(f"Error opening file {file_path}: {e}\n")
        return

    # Find all unique occurrences of #ifdef CONFIG_...
    # The 'set' automatically handles duplicates.
    config_symbols = set(re.findall(r'^\s*#ifdef\s+(CONFIG_\w+)', content, re.MULTILINE))

    # --- Output the generated defines ---
    if config_symbols:
        sys.stdout.write("/*\n")
        sys.stdout.write(" * Automatically generated by doxygen_filter.py\n")
        sys.stdout.write(" * The following symbols are defined to expose all conditional code to Doxygen.\n")
        sys.stdout.write(" */\n")
        for symbol in sorted(list(config_symbols)):
            sys.stdout.write(f"#define {symbol} 1\n")
        sys.stdout.write("\n/* --- End of auto-generated defines --- */\n\n")

    # --- Output the original file content ---
    sys.stdout.write(content)


if __name__ == '__main__':
    if len(sys.argv) > 1:
        process_file(sys.argv[1])
    else:
        sys.stderr.write("Usage: python doxygen_filter.py <file_path>\n")

